meta_product_name: "OJB Production"
meta_title: "OJB Production - Music Producer, Ghostwriter. First Project "NOX", finally is complete!! All written, produced and mixed by OJB."
meta_description: "New Project 'NOX' combines electronic genres and interesting instruments"
meta_image: "harmonys-dub_optimized.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
